name: wastebin

services:
  wastebin:
    image: quxfoo/wastebin:3.7.0
    container_name: wastebin
    volumes:
      - ./data:/data
    environment:
      - WASTEBIN_DATABASE_PATH=/data/state.db
    networks:
      - caddy-proxy
    restart: always
    user: 1000:1000
    # TODO: Add healthcheck
    # NOTE: Image has no shell, no wget/curl
    # NOTE: Need more investigation
    expose:
      - '8088'
networks:
  caddy-proxy:
    external: true
