---
- name: Disable systemd-resolved DNS Stub Listener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNSStubListener='
    line: 'DNSStubListener=no'
  notify: Restart systemd-resolved

- name: Ensure resolv.conf points to upstream
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true

- name: Configure Docker daemon to use reliable upstream DNS
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "dns": ["192.168.20.1", "10.0.0.1"]
      }
    mode: '0644'
  notify: Restart docker
