services:
  openspeedtest:
    restart: unless-stopped
    image: openspeedtest/latest
    expose:
      - 3000  # HTTP Port
      - 3001  # HTTPS Port
    networks:
      - caddy-proxy
networks:
  caddy-proxy:
    external: true
