---
- name: Deploy Caddyfile from template and host_vars
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ compose_deploy_dir }}/{{ item.name }}/Caddyfile"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ compose_apps }}"
  when: item.name == "caddy"
