---
- name: Pull latest Docker images (standard apps)
  community.docker.docker_compose_v2_pull:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
  loop: "{{ compose_apps }}"
  when: not (item.build | default(false))

- name: Build Docker images (build apps)
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    build: always
    state: present
  loop: "{{ compose_apps }}"
  when: item.build | default(false)
  register: build_result

- name: Deploy with Docker Compose (standard apps)
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    state: present
  loop: "{{ compose_apps }}"
  when: not (item.build | default(false))
  register: compose_result

- name: Restart changed build apps
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.item.name }}"
    state: restarted
  loop: "{{ build_result.results }}"
  when:
    - item is not skipped
    - item.changed
  loop_control:
    label: "{{ item.item.name }}"

- name: Restart changed standard apps
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.item.name }}"
    state: restarted
  loop: "{{ compose_result.results }}"
  when:
    - item is not skipped
    - item.changed
  loop_control:
    label: "{{ item.item.name }}"
