---
- name: Pull latest Docker images (standard apps)
  community.docker.docker_compose_v2_pull:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
  loop: "{{ compose_apps }}"
  when: not (item.build | default(false))
  notify: Restart Docker Compose App

- name: Build Docker images (build apps)
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    build: always
    state: present
  loop: "{{ compose_apps }}"
  when: item.build | default(false)
  notify: Restart Docker Compose App

- name: Deploy with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    state: present
  loop: "{{ compose_apps }}"
  notify: >-
    {{
      'Restart Docker Compose App' if (
        (caddy_config_changes is defined and caddy_config_changes.changed) or
        (
          (hostvars[groups['dns'][0]]['bind9_dns_changed'] and item.name == 'bind9') |
           default(false)
        )
      ) else []
    }}
