---
caddy_domain: "test.{{ lab_domain }}"

compose_apps:
  - name: caddy

  - name: dashy
    caddy:
      default:
        host: dashy

  - name: dockge
    caddy:
      default:
        host: dockge

  - name: wetty
    caddy:
      default:
        host: wetty
