compose_apps:
  - name: caddy
    src_dir: ../../../docker/caddy
    exclude:
      - Caddyfile.services
      - Caddyfile.play
    has_env: true
    build: true
  - name: minecraft
    src_dir: ../../../docker/minecraft
  - name: diun
    src_dir: ../../../docker/diun
    has_env: true
