---
caddy_domain: play.example.com

compose_apps:
  - name: caddy
    has_env: true
    build: true

  - name: minecraft
    caddy:
      - host: bluemap
        upstream: bluemap:8100

  - name: diun
    has_env: true
