---
caddy_domain: svc.example.com

cobalt_app_url: cobalt.svc.example.com
shlink_short_url: short.svc.example.com
shlink_web_url: shlink.svc.example.com

compose_apps:
  - name: caddy
    build: true

  - name: bentopdf
    caddy:
      - host: bentopdf

  - name: cobalt
    caddy:
      - host: cobalt

  - name: dashy
    caddy:
      - host: dashy

  - name: kms
    caddy:
      - host: kms

  - name: openspeedtest
    caddy:
      - host: speedtest

  - name: shlink
    caddy:
      - host: shlink
      - host: short

  - name: wastebin
    caddy:
      - host: wastebin

  - name: wetty
    caddy:
      - host: wetty

  - name: diun
