services:
  caddy:
    image: caddy-digitalocean:latest  # Image managed by Ansible
    pull_policy: never                # Local built image only
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp # HTTP/3 support
    environment:
      DO_API_TOKEN: ${DO_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    networks:
      - caddy-proxy
    labels:
      - diun.enable=false
networks:
  caddy-proxy:
    name: caddy-proxy
