name: happy_app_stop
services:
  happy_app_stop:
    image: alpine:3.20
    container_name: happy_app_stop
    volumes:
      - data:/data
    command: [ "sh", "-c", "sleep infinity" ]
    labels:
      - docker-volume-backup.stop-during-backup=true
volumes:
  data:
    external: true
    name: happy_app_stop_data
