services:
  shlink:
    image: shlinkio/shlink:5
    environment:
      DEFAULT_DOMAIN: ${APP_URL}
      DEFAULT_BASE_URL_REDIRECT: ${WEB_APP_URL}
      IS_HTTPS_ENABLED: false
      INITIAL_API_KEY: ${API_KEY}
      # GEOLITE_LICENSE_KEY:
    networks:
      - caddy-proxy
    restart: unless-stopped
    expose:
      - '8080'
  shlink-web-client:
    image: shlinkio/shlink-web-client:4
    environment:
      SHLINK_SERVER_URL: https://${APP_URL}
      SHLINK_SERVER_API_KEY: ${API_KEY}
    networks:
      - caddy-proxy
    restart: unless-stopped
    expose:
      - '8080'
networks:
  caddy-proxy:
    external: true
