name: kms

services:
  kms-app:
    image: 11notes/kms:1.0
    container_name: kms-app
    volumes:
      - ./data:/kms/var
    environment:
      TZ: ${TIMEZONE}
    ports:
      - '0.0.0.0:1688:1688/tcp'
    networks:
      - frontend
    restart: always
    user: 1000:1000
  kms-gui:
    image: 11notes/kms-gui:1.0
    container_name: kms-gui
    depends_on:
      kms-app:
        condition: service_healthy
        restart: true
    volumes:
      - ./data:/kms/var
    environment:
      TZ: ${TIMEZONE}
    networks:
      - frontend
      - caddy-proxy
    restart: always
    user: 1000:1000
    expose:
      - '3000'
networks:
  frontend: {}
  caddy-proxy:
    external: true
