name: beszel-hub

services:
  beszel-hub:
    image: henrygd/beszel:0.18
    container_name: beszel-hub
    volumes:
      - ./data:/beszel_data
    env_file:
      - .env
    networks:
      - caddy-proxy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/beszel", "health", "--url", "http://127.0.0.1:8090" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - '8090'
networks:
  caddy-proxy:
    external: true
