name: beszel-hub

services:
  beszel-hub:
    image: henrygd/beszel:0.18
    container_name: beszel-hub
    volumes:
      - ./data:/beszel_data
    env_file:
      - .env
    networks:
      - caddy-proxy
    restart: unless-stopped
    expose:
      - '8090'
networks:
  caddy-proxy:
    external: true
