services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - caddy-proxy
networks:
  caddy-proxy:
    external: true
