name: cobalt

services:
  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    environment:
      # for tunneling functionality
      API_URL: ${COBALT_API_URL}
      # to use cookies for fetching data from services,
      # uncomment next line & volumes section
      # COOKIE_PATH: "/cookies.json"
      # volumes:
      # - ./cookies.json:/cookies.json
    networks:
      - caddy-proxy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/api/serverInfo" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - '9000'
    init: true
    read_only: true
networks:
  caddy-proxy:
    external: true
