name: happy_app_no_backup
services:
  happy_app_no_backup:
    image: alpine:3.20
    container_name: happy_app_no_backup
    volumes:
      - data:/data
    command: [ "sh", "-c", "sleep infinity" ]
volumes:
  data:
    external: true
    name: happy_app_no_backup_data
