server_timezone: Asia/Singapore

compose_source_dir: ../../../docker
compose_deploy_dir: /opt/stacks

# Docker install settings
docker_users:
  - "{{ ansible_user }}"   # adds SSH user to the docker group
