---
- name: Pull latest Docker images (standard apps)
  community.docker.docker_compose_v2_pull:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
  loop: "{{ compose_apps }}"
  when: not (item.build | default(false))
  tags:
    - pull-docker-images

- name: Build Docker images (build apps)
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    build: always
    state: present
  loop: "{{ compose_apps }}"
  when: item.build | default(false)

- name: Deploy with Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/{{ item.name }}"
    state: present
  loop: "{{ compose_apps }}"

- name: Restart bind9 if DNS config changed
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/bind9"
    state: restarted
  when:
    - inventory_hostname in groups['dns']
    - hostvars[groups['dns'][0]]['bind9_dns_changed'] | default(false)

- name: Restart caddy if config changed
  community.docker.docker_compose_v2:
    project_src: "{{ compose_deploy_dir }}/caddy"
    state: restarted
  when: caddy_config_changes is defined and caddy_config_changes.changed
