name: minecraft

services:
  test-upgrade:
    image: itzg/minecraft-server:java25
    volumes:
      - ./extras:/extras:ro
    environment:
      EULA: "TRUE"
      SETUP_ONLY: true
      VERSION: ${VERSION}
      TYPE: FABRIC
      MODRINTH_LOADER: fabric
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: beta
      MODRINTH_MODPACK: simply-optimized-up-to-date
      MODRINTH_PROJECTS: "@/extras/modrinth-mods.txt"
