name: minecraft

services:
  test-upgrade:
    volumes: !reset
      - /tmp/mc-upgrade-check:/data
    environment:
      SETUP_ONLY: "true"
      VERSION: ${VERSION}
    extends:
      file: compose.yaml
      service: mc
