name: minecraft

services:
  restore-backup:
    image: itzg/mc-backup:2026.6.2
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./data:/data
      # Must be same mount as backups service, but can be read-only
      - ./backups:/backups:ro
    entrypoint: restore-tar-backup
    restart: no
    user: "1000"
