name: minecraft

services:
  backups:
    image: itzg/mc-backup:2026.6.2
    depends_on:
      mc:
        condition: service_healthy
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
    environment:
      CRON_SCHEDULE: "0 4 * * *" # backup everyday at 4am
      CRON_BACKUP_UID: "1000"
      RCON_HOST: mc
    restart: always
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:v5
    volumes:
      - ./bluemap/config:/app/config
      - ./bluemap/web:/app/web
      - ./bluemap/data:/app/data
      - ./data/world:/app/world
    networks:
      - caddy-proxy
    command: -r -u -w
    restart: always
    expose:
      - '8100'
  mc:
    image: itzg/minecraft-server:java25
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 1G
      MAX_MEMORY: 2G
      TYPE: FABRIC
      VERSION: 1.21.11
      MOTD: |
        §l§6🎣 My Forever World 🏹§r
        A %TYPE% server on %VERSION%
      MODRINTH_LOADER: fabric
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: beta # "release"
      MODRINTH_MODPACK: sop # "fabulously-optimized"
      MODRINTH_PROJECTS: |
        fabric-api
        vanilla-permissions
        luckperms
        jade
        replanting-crops
        tree-harvester
        recast
        always-a-wither-skull
        grind-enchantments
        tax-free-levels
        noexpensive
        revault
        invview
        armor-poser
        no-enderman-grief
    ports:
      - '0.0.0.0:25565:25565'
    restart: unless-stopped
    expose:
      - '25575' # RCON port
    stdin_open: true
    tty: true
networks:
  caddy-proxy:
    external: true
