name: minecraft

services:
  restore-backup:
    image: itzg/mc-backup:2026.7.3
    volumes:
      - data:/data
      - backups:/backups:ro
    entrypoint: restore-tar-backup
    restart: no
    user: "1000"
volumes:
  data:
    external: true
    name: minecraft_data
  backups:
    external: true
    name: minecraft_backups
