---
- name: Prepare
  hosts: all
  tasks:
    - name: Reset coverage data from any previous test run
      ansible.builtin.include_role:
        name: molecule_helpers
        tasks_from: reset_coverage_data.yaml

    - name: Clear any secrets cache left over from a previous local run
      ansible.builtin.file:
        path: /tmp/secrets-molecule-manual-missing/ansible/files/secrets/
        state: absent
      delegate_to: localhost
      become: false
