---
- name: Prepare
  hosts: all
  tasks:
    - name: Reset coverage data from any previous test run
      ansible.builtin.include_role:
        name: molecule_helpers
        tasks_from: reset_coverage_data.yaml
