name: lldap

services:
  lldap:
    image: ghcr.io/lldap/lldap:2026-08-08-alpine
    container_name: lldap
    volumes:
      - data:/data
      - certs:/data/certs
    env_file:
      - .env
    ports:
      - '0.0.0.0:6360:6360' # For LDAPS (LDAP Over SSL)
    networks:
      - caddy-proxy
    restart: unless-stopped
    expose:
      - '17170' # Web front-end
networks:
  caddy-proxy:
    external: true
volumes:
  data:
    external: true
    name: lldap_data
  certs:
    external: true
    name: lldap_certs
