services:
  dashy:
    image: lissy93/dashy:latest
    user: "1000:1000"
    expose:
      - 8080
    volumes:
      - ./user-data:/app/user-data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - node
        - /app/services/healthcheck.js
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - caddy-proxy
networks:
  caddy-proxy:
    external: true
