name: lldap

services:
  certbot:
    image: certbot/dns-digitalocean:amd64-latest
    container_name: lldap-certbot
    depends_on:
      - dockerproxy
    volumes:
      - ./letsencrypt/conf:/etc/letsencrypt
      - ./letsencrypt/lib:/var/lib/letsencrypt
      - ./creds:/creds
      - ./scripts:/scripts
      - ./certs:/output-certs
      - ./scripts/deploy-hook.sh:/etc/letsencrypt/renewal-hooks/deploy/deploy-hook.sh:ro
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
    env_file:
      - .env
    networks:
      - docker-socket-proxy-net
    entrypoint: /scripts/entrypoint.sh
    restart: unless-stopped
    # TODO: Add healthcheck
    # NOTE: Just loops the renewal script, no daemon/port to probe
    # NOTE: Need more investigation
  dockerproxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: lldap-dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - docker-socket-proxy-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2375/version" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
  lldap:
    image: lldap/lldap:latest-alpine
    container_name: lldap
    volumes:
      - ./data:/data
      - ./certs:/data/certs
    env_file:
      - .env
    ports:
      - '0.0.0.0:6360:6360' # For LDAPS (LDAP Over SSL)
    networks:
      - caddy-proxy
    restart: unless-stopped
    expose:
      - '17170' # Web front-end
networks:
  caddy-proxy:
    external: true
  docker-socket-proxy-net:
    internal: true
