#!/usr/bin/env python3
"""Interactively fill in every missing `manual`-format secret, once.

Run before your first `ansible-playbook deploy.yaml`. Only touches
`format: manual` entries in secrets_registry.yaml — hex/uuid4 entries are
generated by the `secrets` role itself.

Most `manual` entries have a `vault_scope` and are stored in OpenBao;
main-domain and openbao-controller-role-id/-secret-id don't, and stay in
the controller-side file cache instead (see secrets_registry.yaml's own
header comment for why — Vault access itself depends on them). Vault-
backed entries need OpenBao reachable and the controller AppRole already
provisioned (docs/openbao-auth.md's runbook) before this script can do
anything with them.

Every cloudflare-r2-*/backblaze-b2-*/oci-* entry has a vault_scope too
(cloud_credentials/leaf) but is deliberately excluded from this script's
own manual-entry handling below — `create_leaf_keys.py`/
`create_rotation_keys.py` own those, with their own provider-specific
minting and verify-before-trust logic (e.g. a real `rclone lsjson`
against the actual bucket). Letting this script's generic prompt-and-
write path also touch the same Vault paths would mean two independently-
written mechanisms both claiming to be authoritative for the same
credential, with only one of them actually verifying what it stores. See
docs/cloud-credential-creation.md for how those are created instead.

Safe to re-run: an entry that already has a value (on disk, or in Vault)
is left untouched. To rotate a value, see docs/secrets-rotation.md.

Uses hvac for the OpenBao client and paramiko for the SSH root-cert
fetch, via the shared primitives in tools/openbao_utils/client.py -
this script has no SSH/paramiko code of its own left. See
docs/decisions/0030-openbao-client-implementation-in-repo-python/revision-000.md and
docs/decisions/0031-where-repo-tooling-lives/revision-000.md.

Usage:
    cd tools && python3 -m openbao_utils.bootstrap
    # or, if you manage the project with uv:
    cd tools && uv run python3 -m openbao_utils.bootstrap
"""

from __future__ import annotations

import getpass
import sys
import tempfile
from pathlib import Path

import hvac
import yaml
from cloud_credentials._legacy_cache_keys import LEGACY_CACHE_KEYS
from utils.repo import PROJECT_ROOT, SECRETS_DIR, TIMEOUT_SECONDS, fetch_root_cert, read_bootstrap_file

from openbao_utils.client import openbao_base_url, vault_read, vault_write
from openbao_utils.client import vault_login as _bare_vault_login

REGISTRY_PATH = PROJECT_ROOT / "ansible/inventory/group_vars/all/secrets_registry.yaml"


def load_registry() -> dict[str, dict]:
    with REGISTRY_PATH.open() as f:
        return yaml.safe_load(f)["secrets_registry"]


# Names create_leaf_keys.py/create_rotation_keys.py own (see this
# module's own docstring) - reusing cloud_credentials' own canonical
# list rather than a second, hand-maintained one here, so the two can't
# drift the way secrets_registry.yaml's header comment and this script's
# actual behavior once did.
#
# LEGACY_CACHE_KEYS also tracks operator-provided values (region/
# namespace/account-id) that live in the same Vault-backed cache but
# have no automated writer at all - create_leaf_keys.py never mints
# them, it only reads them. Excluding those too would mean nothing in
# this project ever prompts for them.
_OPERATOR_PROVIDED_NAMES = frozenset(
    {
        "backblaze-b2-region",
        "oci-namespace",
        "oci-region",
        "cloudflare-r2-account-id",
    }
)
_CLOUD_CREDENTIAL_OWNED_NAMES = frozenset(name for name, _module in LEGACY_CACHE_KEYS) - _OPERATOR_PROVIDED_NAMES


def load_manual_entries(registry: dict) -> dict[str, dict]:
    return {name: spec for name, spec in registry.items() if spec.get("format") == "manual" and name not in _CLOUD_CREDENTIAL_OWNED_NAMES}


def read_cache_file(name: str) -> str | None:
    path = SECRETS_DIR / name
    return path.read_text() if path.exists() else None


def prompt_for_value(name: str, spec: dict) -> str:
    description = spec.get("description", "(no description in secrets_registry.yaml)")
    sensitive = spec.get("sensitive", False)
    allow_blank = spec.get("allow_blank", False)

    print(f"\n{name}")
    print(f"  {description}")

    reader = (lambda: getpass.getpass("  value (input hidden): ")) if sensitive else (lambda: input("  value: "))

    if allow_blank:
        print("  This one doesn't have to be known yet — press Enter to leave it")
        print("  blank for now (see the description above for when/how to fill")
        print("  it in later; just re-run this script once you have the value).")
        return reader()

    while True:
        value = reader()
        if value.strip():
            return value
        print("  This one can't be left blank — a blank value here would silently")
        print("  break whatever consumes it, with no clear error. Try again.")


# --- Vault plumbing --------------------------------------------------------
# fetch_root_cert/vault_read/vault_write come from openbao_utils.client -
# shared with cloud_credentials/cache.py, no longer duplicated between
# them. Only the login wrapper stays here: it reads this script's own
# role_id/secret_id before calling the shared bare login.


def vault_login(client: hvac.Client) -> None:
    role_id = read_bootstrap_file("openbao-controller-role-id")
    secret_id = read_bootstrap_file("openbao-controller-secret-id")
    if not role_id or not secret_id:
        print(
            "openbao-controller-role-id/-secret-id aren't set yet — run "
            "docs/openbao-auth.md's runbook (Track A stage 3) before "
            "bootstrapping any Vault-backed manual secret.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    _bare_vault_login(client, role_id, secret_id)


def main() -> int:
    if not REGISTRY_PATH.exists():
        print(f"Registry not found at {REGISTRY_PATH}", file=sys.stderr)
        return 1

    registry = load_registry()
    manual_entries = load_manual_entries(registry)
    if not manual_entries:
        print("No manual-format entries in secrets_registry.yaml — nothing to do.")
        return 0

    SECRETS_DIR.mkdir(parents=True, mode=0o700, exist_ok=True)

    vault_entries = {name: spec for name, spec in manual_entries.items() if "vault_scope" in spec}
    file_entries = {name: spec for name, spec in manual_entries.items() if "vault_scope" not in spec}

    created_file: list[str] = []
    skipped: list[str] = []
    left_blank: list[str] = []

    for name, spec in file_entries.items():
        dest = SECRETS_DIR / name
        if dest.exists():
            skipped.append(name)
            continue
        try:
            value = prompt_for_value(name, spec)
        except KeyboardInterrupt, EOFError:
            print("\nAborted — nothing further was written.", file=sys.stderr)
            return 1
        dest.write_text(value)
        dest.chmod(0o600)
        created_file.append(name)
        if not value.strip():
            left_blank.append(name)

    created_vault: list[str] = []

    if vault_entries:
        ca_path: str | None = None
        try:
            with tempfile.NamedTemporaryFile("w", suffix="-openbao-root-ca", delete=False) as f:
                f.write(fetch_root_cert())
                ca_path = f.name
            client = hvac.Client(url=openbao_base_url(), verify=ca_path, timeout=TIMEOUT_SECONDS)
            vault_login(client)

            for name, spec in vault_entries.items():
                vault_path = f"{spec['vault_scope']}/{name}"
                if vault_read(client, vault_path) is not None:
                    skipped.append(name)
                    continue
                try:
                    value = prompt_for_value(name, spec)
                except KeyboardInterrupt, EOFError:
                    print("\nAborted — nothing further was written.", file=sys.stderr)
                    return 1
                vault_write(client, vault_path, value)
                created_vault.append(name)
                if not value.strip():
                    left_blank.append(name)
        finally:
            if ca_path:
                Path(ca_path).unlink(missing_ok=True)

    print("\n--- Summary ---")
    if created_file:
        print(f"Created (file cache): {', '.join(created_file)}")
    if created_vault:
        print(f"Created (OpenBao): {', '.join(created_vault)}")
    if skipped:
        print(f"Already set (untouched): {', '.join(skipped)}")
    if left_blank:
        print(f"Left blank on purpose: {', '.join(left_blank)}")
        print("Re-run this script after you have real values for these — an existing entry, even a blank one, is never re-prompted for automatically.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
