name: step-ca

services:
  step-ca:
    image: smallstep/step-ca:0.30.2
    container_name: step-ca
    volumes:
      - data:/home/step
      - scripts:/scripts
    env_file:
      - .env
    networks:
      - caddy-proxy
    entrypoint: /scripts/entrypoint.sh
    restart: unless-stopped
    expose:
      - '9000'
networks:
  caddy-proxy:
    external: true
volumes:
  data:
    external: true
    name: step-ca_data
  scripts:
    external: true
    name: step-ca_scripts
