services:
  caddy:
    image: caddy-digitalocean:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp # HTTP/3 support
    environment:
      DO_API_TOKEN: ${DO_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    networks:
      - caddy-proxy
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:builder AS builder
        RUN xcaddy build --with github.com/caddy-dns/digitalocean
        FROM caddy:latest
        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    labels:
      - diun.enable=false
networks:
  caddy-proxy:
    name: caddy-proxy
