#!/usr/bin/env python3
"""Interactively fill in every missing `manual`-format secret, once.

Run before your first `ansible-playbook deploy.yaml`. Only touches
`format: manual` entries in secrets_registry.yaml — hex/uuid4 entries are
generated by the `secrets` role itself.

Most `manual` entries have a `vault_scope` and are stored in OpenBao;
main-domain and openbao-controller-role-id/-secret-id don't, and stay in
the controller-side file cache instead (see secrets_registry.yaml's own
header comment for why — Vault access itself depends on them). Vault-
backed entries need OpenBao reachable and the controller AppRole already
provisioned (docs/openbao-auth.md's runbook) before this script can do
anything with them.

Every cloudflare-r2-*/backblaze-b2-*/oci-* entry has a vault_scope too
(cloud_credentials/leaf) but is deliberately excluded from this script's
own manual-entry handling below — `create_leaf_keys.py`/
`create_rotation_keys.py` own those, with their own provider-specific
minting and verify-before-trust logic (e.g. a real `rclone lsjson`
against the actual bucket). Letting this script's generic prompt-and-
write path also touch the same Vault paths would mean two independently-
written mechanisms both claiming to be authoritative for the same
credential, with only one of them actually verifying what it stores. See
docs/cloud-credential-creation.md for how those are created instead.

Safe to re-run: an entry that already has a value (on disk, or in Vault)
is left untouched. To rotate a value, see docs/secrets-rotation.md.

Usage:
    python3 ansible/bootstrap_secrets.py
    # or, if you manage the project with uv:
    uv run python3 ansible/bootstrap_secrets.py
"""

from __future__ import annotations

import getpass
import subprocess
import sys
import tempfile
from pathlib import Path

import requests
import yaml
from cloud_credentials._legacy_cache_keys import LEGACY_CACHE_KEYS

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = PROJECT_ROOT / "ansible/inventory/group_vars/all/secrets_registry.yaml"
SECRETS_DIR = PROJECT_ROOT / "ansible/files/secrets"
INVENTORY_PATH = PROJECT_ROOT / "ansible/inventory/inventory.yaml"

VAULT_KV_MOUNT = "secret"
VAULT_STEP_CA_CONTAINER = "step-ca"


def load_registry() -> dict[str, dict]:
    with REGISTRY_PATH.open() as f:
        return yaml.safe_load(f)["secrets_registry"]


# Names create_leaf_keys.py/create_rotation_keys.py own (see this
# module's own docstring) - reusing cloud_credentials' own canonical
# list rather than a second, hand-maintained one here, so the two can't
# drift the way secrets_registry.yaml's header comment and this script's
# actual behavior once did.
_CLOUD_CREDENTIAL_OWNED_NAMES = frozenset(name for name, _module in LEGACY_CACHE_KEYS)


def load_manual_entries(registry: dict) -> dict[str, dict]:
    return {name: spec for name, spec in registry.items() if spec.get("format") == "manual" and name not in _CLOUD_CREDENTIAL_OWNED_NAMES}


def read_cache_file(name: str) -> str | None:
    path = SECRETS_DIR / name
    return path.read_text() if path.exists() else None


def prompt_for_value(name: str, spec: dict) -> str:
    description = spec.get("description", "(no description in secrets_registry.yaml)")
    sensitive = spec.get("sensitive", False)
    allow_blank = spec.get("allow_blank", False)

    print(f"\n{name}")
    print(f"  {description}")

    reader = (lambda: getpass.getpass("  value (input hidden): ")) if sensitive else (lambda: input("  value: "))

    if allow_blank:
        print("  This one doesn't have to be known yet — press Enter to leave it")
        print("  blank for now (see the description above for when/how to fill")
        print("  it in later; just re-run this script once you have the value).")
        return reader()

    while True:
        value = reader()
        if value.strip():
            return value
        print("  This one can't be left blank — a blank value here would silently")
        print("  break whatever consumes it, with no clear error. Try again.")


# --- Vault plumbing --------------------------------------------------------
# Mirrors docs/decisions/0025-controller-vault-tls-trust-via-per-run-fetched-root-cert.md's
# Ansible-side mechanism (fetch step-ca's root cert fresh every run, never
# skip-verify, never committed) — this script runs standalone, outside any
# Ansible play, so it has to do the SSH/docker-exec/tempfile steps itself
# rather than delegating to that role.


def _main_domain() -> str:
    main_domain = read_cache_file("main-domain")
    if not main_domain or not main_domain.strip():
        print(
            "main-domain isn't cached yet — it's needed to reach OpenBao at "
            "all (secrets_registry.yaml's header comment explains why it "
            "never moves into Vault). Set it first:\n"
            f"  printf '%s' '<your-domain>' > {SECRETS_DIR / 'main-domain'}\n"
            f"  chmod 600 {SECRETS_DIR / 'main-domain'}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    return main_domain.strip()


def _openbao_base_url() -> str:
    # security's caddy_domain = "sec.{{ lab_domain }}", lab_domain =
    # "lan.{{ main_domain }}" (host_vars/security.yaml,
    # group_vars/all/main.yaml). Duplicated here rather than templated
    # through Ansible, since this script runs before any Ansible play —
    # update this if either file's naming convention ever changes.
    return f"https://openbao.sec.lan.{_main_domain()}:8200"


def _security_ssh_target() -> tuple[str, str, str]:
    """(user, host, key_path) for SSH to `security`, read from
    inventory.yaml rather than hardcoded twice."""
    with INVENTORY_PATH.open() as f:
        inv = yaml.safe_load(f)
    user = inv["all"]["children"]["managed_hosts"]["hosts"]["security"]["ansible_user"]
    key_path = Path(inv["all"]["vars"]["ansible_ssh_private_key_file"]).expanduser()
    host = f"security.internal.{_main_domain()}"  # ddns_domain, see inventory.yaml
    return user, host, str(key_path)


def fetch_root_cert() -> str:
    user, host, key_path = _security_ssh_target()
    result = subprocess.run(
        [
            "ssh",
            "-i",
            key_path,
            "-o",
            "StrictHostKeyChecking=accept-new",
            f"{user}@{host}",
            "docker",
            "exec",
            VAULT_STEP_CA_CONTAINER,
            "cat",
            "/home/step/certs/root_ca.crt",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(f"Failed to fetch step-ca's root cert from {host}: {result.stderr}", file=sys.stderr)
        raise SystemExit(1)
    return result.stdout


def vault_login(ca_path: str) -> str:
    role_id = read_cache_file("openbao-controller-role-id")
    secret_id = read_cache_file("openbao-controller-secret-id")
    if not role_id or not role_id.strip() or not secret_id or not secret_id.strip():
        print(
            "openbao-controller-role-id/-secret-id aren't set yet — run "
            "docs/openbao-auth.md's runbook (Track A stage 3) before "
            "bootstrapping any Vault-backed manual secret.",
            file=sys.stderr,
        )
        raise SystemExit(1)
    resp = requests.post(
        f"{_openbao_base_url()}/v1/auth/approle/login",
        json={"role_id": role_id.strip(), "secret_id": secret_id.strip()},
        verify=ca_path,
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()["auth"]["client_token"]


def vault_read(token: str, ca_path: str, vault_path: str) -> str | None:
    resp = requests.get(
        f"{_openbao_base_url()}/v1/{VAULT_KV_MOUNT}/data/{vault_path}",
        headers={"X-Vault-Token": token},
        verify=ca_path,
        timeout=10,
    )
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    return resp.json()["data"]["data"]["value"]


def vault_write(token: str, ca_path: str, vault_path: str, value: str) -> None:
    resp = requests.post(
        f"{_openbao_base_url()}/v1/{VAULT_KV_MOUNT}/data/{vault_path}",
        headers={"X-Vault-Token": token},
        json={"data": {"value": value}},
        verify=ca_path,
        timeout=10,
    )
    resp.raise_for_status()


def main() -> int:
    if not REGISTRY_PATH.exists():
        print(f"Registry not found at {REGISTRY_PATH}", file=sys.stderr)
        return 1

    registry = load_registry()
    manual_entries = load_manual_entries(registry)
    if not manual_entries:
        print("No manual-format entries in secrets_registry.yaml — nothing to do.")
        return 0

    SECRETS_DIR.mkdir(parents=True, mode=0o700, exist_ok=True)

    vault_entries = {name: spec for name, spec in manual_entries.items() if "vault_scope" in spec}
    file_entries = {name: spec for name, spec in manual_entries.items() if "vault_scope" not in spec}

    created_file: list[str] = []
    skipped: list[str] = []
    left_blank: list[str] = []

    for name, spec in file_entries.items():
        dest = SECRETS_DIR / name
        if dest.exists():
            skipped.append(name)
            continue
        try:
            value = prompt_for_value(name, spec)
        except KeyboardInterrupt, EOFError:
            print("\nAborted — nothing further was written.", file=sys.stderr)
            return 1
        dest.write_text(value)
        dest.chmod(0o600)
        created_file.append(name)
        if not value.strip():
            left_blank.append(name)

    created_vault: list[str] = []

    if vault_entries:
        ca_path: str | None = None
        try:
            with tempfile.NamedTemporaryFile("w", suffix="-openbao-root-ca", delete=False) as f:
                f.write(fetch_root_cert())
                ca_path = f.name
            token = vault_login(ca_path)

            for name, spec in vault_entries.items():
                vault_path = f"{spec['vault_scope']}/{name}"
                if vault_read(token, ca_path, vault_path) is not None:
                    skipped.append(name)
                    continue
                try:
                    value = prompt_for_value(name, spec)
                except KeyboardInterrupt, EOFError:
                    print("\nAborted — nothing further was written.", file=sys.stderr)
                    return 1
                vault_write(token, ca_path, vault_path, value)
                created_vault.append(name)
                if not value.strip():
                    left_blank.append(name)
        finally:
            if ca_path:
                Path(ca_path).unlink(missing_ok=True)

    print("\n--- Summary ---")
    if created_file:
        print(f"Created (file cache): {', '.join(created_file)}")
    if created_vault:
        print(f"Created (OpenBao): {', '.join(created_vault)}")
    if skipped:
        print(f"Already set (untouched): {', '.join(skipped)}")
    if left_blank:
        print(f"Left blank on purpose: {', '.join(left_blank)}")
        print("Re-run this script after you have real values for these — an existing entry, even a blank one, is never re-prompted for automatically.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
