---
collections:
  - name: community.docker
    version: "5.4.0"
  - name: ansible.posix
    version: "2.2.2"
  - name: amazon.aws
    version: "11.4.0"
  - name: community.hashi_vault
    version: "7.1.0"
  - name: community.crypto
    version: "3.5.0"
  - name: konstruktoid.hardening
    version: "0.4.0"
  - name: community.general
    version: "13.5.0"
