name: wetty

services:
  wetty:
    image: wettyoss/wetty:main
    environment:
      SSHHOST: ${DEFAULT_SSH_HOST}
      NODE_ENV: production
    networks:
      - caddy-proxy
    command:
      - --base=/
      - --allow-remote-hosts
    working_dir: /usr/src/app
    restart: always
    expose:
      - '3000'
    tty: true
networks:
  caddy-proxy:
    external: true
