name: wetty

services:
  wetty:
    image: wettyoss/wetty:main
    environment:
      SSHHOST: ${DEFAULT_SSH_HOST}
      NODE_ENV: production
    networks:
      - caddy-proxy
    command:
      - --base=/
      - --allow-remote-hosts
    working_dir: /usr/src/app
    restart: always
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://wetty:3000/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    expose:
      - '3000'
    tty: true
networks:
  caddy-proxy:
    external: true
