services:
  bind9:
    image: ubuntu/bind9:latest
    restart: unless-stopped
    user: 100:101
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
    command: ["named", "-g", "-u", "bind", "-4"]
