name: bind9

services:
  bind9:
    image: ubuntu/bind9:9.20-26.04_edge
    volumes:
      - ./config:/etc/bind
      - ./cache:/var/cache/bind
      - ./records:/var/lib/bind
      - ./run:/run/named
    environment:
      - TZ=${TIMEZONE}
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
    command: [ "--args", "dns-server", "-g", "-u", "bind", "-4" ]
    restart: unless-stopped
    user: bind:bind
