name: tinyauth

services:
  tinyauth:
    image: ghcr.io/tinyauthapp/tinyauth:v5
    container_name: tinyauth
    volumes:
      - ./data:/data
    environment:
      - TINYAUTH_CONFIGFILE=/data/config.yaml
    networks:
      - caddy-proxy
    restart: unless-stopped
networks:
  caddy-proxy:
    external: true
