name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.3
    container_name: uptime-kuma
    volumes:
      - data:/app/data
    networks:
      - caddy-proxy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "extra/healthcheck" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    labels:
      - docker-volume-backup.stop-during-backup=uptime-kuma
    expose:
      - '3001'
networks:
  caddy-proxy:
    external: true
volumes:
  data:
    external: true
    name: uptime-kuma_data
